### ISSUE TITLE
[HELP] 在WSL2环境中构建失败

### ISSUE THREAD

**Issue by yusangeng** [open-vela/docs#19]
### Description

环境已经按要求安装，执行build.sh脚本失败，详细报错：
![image](https://github.com/user-attachments/assets/1f9d3ab2-820c-4ee8-b4fb-46cc6e6c5f0f)

目前是不是不支持在wsl环境中编译？

**Comment by tanghao-xiaomi** [comment]
您好，目前 wsl 不在支持范围

**Comment by hanfengcan** [comment]
> 您好，目前 wsl 不在支持范围

这么久了，WSL支持了吗？
