### ISSUE TITLE
有没有支持OpenVela JS 应用开发的IDE

### ISSUE THREAD

**Issue by zhangshihan918** [open-vela/docs#21]
### Is your feature request related to a problem? Please describe.

有没有支持OpenVela JS 应用开发的IDE

### Describe the solution you'd like

有没有支持OpenVela JS 应用开发的IDE

**Comment by yaotaiyang** [comment]
see here：https://iot.mi.com/vela/quickapp/zh/tools/

**Comment by OnesoftQwQ** [comment]
Visual Studio Code
